### ISSUE TITLE
Build the Poweramp_api_example

### ISSUE THREAD

**Issue by theoklink** [maxmpz/powerampapi#21] opened 2019-01-09 13:59 UTC

**Comment by theoklink** [comment] 2019-01-09 14:03
After importing the Poweramp_api_example into Android Studio the build fails with:

Execution failed for task ':poweramp_api_lib:processDebugManifest'.
> org.xml.sax.SAXParseException; systemId: file:/C:/Temp/powerampapi-master/poweramp_api_example/poweramp_api_lib/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

This error is also encountered by someone who has newly installed Android Studio.
Retyping the manifest content does not resolve the issue.

Same error with
 gradlew lint

**Comment by Jandalf81** [comment] 2019-01-09 18:25
I am that other guy.

Here's how to reproduce the error we are experiencing:
* download 'PowerAmp API' from here: https://github.com/maxmpz/powerampapi/archive/master.zip
* unzip the downloaded file (I put the files onto D:\)
* start Android Studio (version 3.2.1 running on Win 10 64 bit)
* use 'Open an existing Android Studio project', open 'D:\powerampapi-master\poweramp_api_example'
* upon opening, Android Studio will start a 'Build: Sync'
* this Build process fails with the following error message

> Cause: org.xml.sax.SAXParseException; systemId: file:/D:/powerampapi-master/poweramp_api_example/poweramp_api_lib/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
> Content ist nicht zulässig in Prolog.

* looking at the file 'D:/powerampapi-master/poweramp_api_example/poweramp_api_lib/src/main/AndroidManifest.xml' within Android Studio there's no apparent formatting or spelling error
* There are a bunch of other errors:
    * line 3: xmlns:android="http://schemas.android.com/apk/res/android" -> URI is not registered (Settings | Languages and frameworks | Schemas and DTDs)
    * line 5: android:versionCode="1" -> Attribute android:versionCode is not allowed here
    * line 11: android:icon="@mipmap/app_icon" -> Attribute android:icon is not allowed here
    * line 17: android:name=".MainActivity" -> Unresolved class 'MainActivity' (curiously, the android:name Attribute works here)

I can create a new project without problems:
* File -> New -> New Project...
* Phone and Tablet -> API 23: Android 6.0 (Marshmallow)
* Empty Activity
* Finish
* Run app in AVD (Pixel 2, API 28)

I tried to copy the AndroidManifest.xml from the created project into the API example. I keep getting the same errors there, so I think the culprit is not within that file. The API example project seems to be missing a reference to the Android XML namespace, I think.

I _think_ the error lies within the Project Structure... If I open that and look at 'modules' there, the API example is missing several tabs describing how to compile the project (look at the 3rd and the 6th attached screenshot). Now look at the last attached screenshot and you see  that the dropdown between 'build' and 'run' is empty in the API example. This might be another symptom, though, as I am an utter noob on Android...

Project Structure from a new project:
![myapp_1_sdk-location](https://user-images.githubusercontent.com/41969078/50919526-556bc000-1443-11e9-8a0a-582928f99da2.jpg)
![myapp_2_project](https://user-images.githubusercontent.com/41969078/50919527-556bc000-1443-11e9-9c8c-fb1e31f39eaf.jpg)
![myapp_3_modules](https://user-images.githubusercontent.com/41969078/50919528-556bc000-1443-11e9-9133-78f4125e38a3.jpg)

Project Structure from pweramp_api_example:
![pae_1_sdk-location](https://user-images.githubusercontent.com/41969078/50919529-556bc000-1443-11e9-9e28-3e3084fd3b7a.jpg)
![pae_2_project](https://user-images.githubusercontent.com/41969078/50919530-56045680-1443-11e9-8e28-7afa4a543b8c.jpg)
![pae_3_modules](https://user-images.githubusercontent.com/41969078/50919531-56045680-1443-11e9-923a-7666d510ff86.jpg)

Difference in build dropdown:
![build](https://user-images.githubusercontent.com/41969078/50919702-cf03ae00-1443-11e9-8dcb-21cdee46bb15.jpg)

**Comment by maxmpz** [comment] 2019-01-10 17:17
Poweramp api example project is structured in the way it kind-of-contains poweramp_api_lib, but actually it's a set of symbolic links to AndroidManifest.xml file + sources folders "redirected" to poweramp_api_lib.

I will simplify this structure a bit asap, but you may solve this by copying /poweramp_api_lib/src/main/AndroidManifest.xml and res folder to /poweramp_api_example/poweramp_api_lib/src/main

**Comment by Jandalf81** [comment] 2019-01-10 17:41
Yeah, that works! I can build and run the API example project now!

I also removed the 'uses-sdk' tags from both AndroidManifest.xml to remove another two warnings.

**Comment by maxmpz** [comment] 2019-01-10 18:21
Should be fixed by 671c0f881e12b6668edce0e846da5098e3cc48af

**Closed by maxmpz** 2019-01-10 18:21 UTC
